INSERT INTO `statements` (`modelID`, `subject`, `predicate`, `object`, `l_language`, `author`, `stread`, `stedit`, `stdelete`) VALUES
(7, 'http://www.tao.lu/Ontologies/generis.rdf#Multiple', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#Property', '',  'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(7, 'http://www.tao.lu/Ontologies/generis.rdf#Multiple', 'http://www.w3.org/2000/01/rdf-schema#label', 'Is language dependent?', 'EN',  'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(7, 'http://www.tao.lu/Ontologies/generis.rdf#Multiple', 'http://www.w3.org/2000/01/rdf-schema#comment', 'Multiple', 'EN',  'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(7, 'http://www.tao.lu/Ontologies/generis.rdf#Multiple', 'http://www.w3.org/2000/01/rdf-schema#domain', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#Property', '', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(7, 'http://www.tao.lu/Ontologies/generis.rdf#Multiple', 'http://www.w3.org/2000/01/rdf-schema#range', 'http://www.tao.lu/Ontologies/generis.rdf#Boolean', '',  'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(7, 'http://www.tao.lu/Ontologies/generis.rdf#Multiple', 'http://www.tao.lu/datatypes/WidgetDefinitions.rdf#widget', 'http://www.tao.lu/datatypes/WidgetDefinitions.rdf#RadioBox', '', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]');

INSERT INTO `statements` (`modelID`, `subject`, `predicate`, `object`, `l_language`, `author`, `stread`, `stedit`, `stdelete`) VALUES
(11, "http://www.tao.lu/Ontologies/TAOGroup.rdf#Members", "http://www.tao.lu/Ontologies/generis.rdf#Multiple", "http://www.tao.lu/Ontologies/generis.rdf#True", '',  'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(11, "http://www.tao.lu/Ontologies/TAOGroup.rdf#Deliveries", "http://www.tao.lu/Ontologies/generis.rdf#Multiple", "http://www.tao.lu/Ontologies/generis.rdf#True", '',  'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(14, "http://www.tao.lu/Ontologies/TAODelivery.rdf#ExcludedSubjects", "http://www.tao.lu/Ontologies/generis.rdf#Multiple", "http://www.tao.lu/Ontologies/generis.rdf#True", '',  'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(14, "http://www.tao.lu/Ontologies/TAODelivery.rdf#ExcludedGroups", "http://www.tao.lu/Ontologies/generis.rdf#Multiple", "http://www.tao.lu/Ontologies/generis.rdf#True", '',  'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(14, "http://www.tao.lu/Ontologies/TAODelivery.rdf#Campaign", "http://www.tao.lu/Ontologies/generis.rdf#Multiple", "http://www.tao.lu/Ontologies/generis.rdf#True", '',  'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]');

INSERT INTO `statements` (`modelID`, `subject`, `predicate`, `object`, `l_language`, `author`, `stread`, `stedit`, `stdelete`) VALUES
(15, "http://www.tao.lu/middleware/wfEngine.rdf#PropertyServiceDefinitionsFormalParameterIn", "http://www.tao.lu/Ontologies/generis.rdf#Multiple", "http://www.tao.lu/Ontologies/generis.rdf#True", '',  'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, "http://www.tao.lu/middleware/wfEngine.rdf#PropertyProcessInstancesCurrentToken", "http://www.tao.lu/Ontologies/generis.rdf#Multiple", "http://www.tao.lu/Ontologies/generis.rdf#True", '',  'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, "http://www.tao.lu/middleware/wfEngine.rdf#PropertyProcessActivities", "http://www.tao.lu/Ontologies/generis.rdf#Multiple", "http://www.tao.lu/Ontologies/generis.rdf#True", '',  'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, "http://www.tao.lu/middleware/wfEngine.rdf#PropertyCallOfServicesActualParameterOut", "http://www.tao.lu/Ontologies/generis.rdf#Multiple", "http://www.tao.lu/Ontologies/generis.rdf#True", '',  'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, "http://www.tao.lu/middleware/wfEngine.rdf#PropertyServiceDefinitionsFormalParameterOut", "http://www.tao.lu/Ontologies/generis.rdf#Multiple", "http://www.tao.lu/Ontologies/generis.rdf#True", '',  'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, "http://www.tao.lu/middleware/wfEngine.rdf#PropertyCallOfServicesActualParameterin", "http://www.tao.lu/Ontologies/generis.rdf#Multiple", "http://www.tao.lu/Ontologies/generis.rdf#True", '',  'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, "http://www.tao.lu/middleware/wfEngine.rdf#PropertyConnectorsNextActivities", "http://www.tao.lu/Ontologies/generis.rdf#Multiple", "http://www.tao.lu/Ontologies/generis.rdf#True", '',  'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, "http://www.tao.lu/middleware/wfEngine.rdf#PropertyConnectorsPreviousActivities", "http://www.tao.lu/Ontologies/generis.rdf#Multiple", "http://www.tao.lu/Ontologies/generis.rdf#True", '',  'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, "http://www.tao.lu/middleware/wfEngine.rdf#PropertyProcessVariables", "http://www.tao.lu/Ontologies/generis.rdf#Multiple", "http://www.tao.lu/Ontologies/generis.rdf#True", '',  'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, "http://www.tao.lu/middleware/wfEngine.rdf#PropertyActivitiesInteractiveServices", "http://www.tao.lu/Ontologies/generis.rdf#Multiple", "http://www.tao.lu/Ontologies/generis.rdf#True", '',  'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, "http://www.tao.lu/middleware/wfEngine.rdf#PropertyConnectorsNotificationModes", "http://www.tao.lu/Ontologies/generis.rdf#Multiple", "http://www.tao.lu/Ontologies/generis.rdf#True", '',  'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, "http://www.tao.lu/middleware/wfEngine.rdf#PropertyActivitiesControls", "http://www.tao.lu/Ontologies/generis.rdf#Multiple", "http://www.tao.lu/Ontologies/generis.rdf#True", '',  'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]');