
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyTransitionRulesThen" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#ClassCallOfservicesResources" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#ClassServiceDefinitionResources" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#ClassProcessDefinitionResources" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#ClassServicesResources" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#ClassProcessExecutionResources" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#ClassTransitionRules" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyServiceDefinitionsFormalParameterIn" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyActivitiesInitial"
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#InstanceStatusPaused"
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyProcessInstancesCurrentToken" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyProcessInstancesStatus" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#InstanceStatusFinished" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#InstanceStatusResumed" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#InstanceStatusStarted" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#ClassProcessInstanceStatus" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyProcessInstancesExecutionOf" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#ClassProcessInstances" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyProcessActivities" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyCallOfServicesActualParameterOut" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyServiceDefinitionsFormalParameterOut" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyConnectorsType" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyCallOfServicesActualParameterin" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyCallOfServicesServiceDefinition" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#ClassCallOfServices" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyConnectorsNextActivities" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyConnectorsPreviousActivities" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#InstanceTypeOfConnectorsSequence" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#InstanceTypeOfConnectorsConditional" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#InstanceTypeOfConnectorsParallel" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#InstanceTypeOfConnectorsJoin" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#ClassConnectors" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyProcessVariables" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#ClassTypeOfConnectors" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyActualParametersProcessVariable" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyActualParametersConstantValue" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#ClassProcessVariables" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyActualParametersFormalParameter" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyFormalParametersDefaultConstantValue" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyFormalParametersDefaultProcessVariable" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#ClassActualParameters" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyFormalParameterDataType" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyFormalParametersName" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#ClassFormalParameters" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertySupportServicesUrl" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyWebServicesWsdlUrl" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#ClassRole" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyFormalParameterName" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyActivitiesInteractiveServices" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#ClassSupportServices" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#ClassWebServices" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#ClassServiceDefinitions" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#ClassActivities" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#ClassProcessDefinitions" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyConnectorsTransitionRule" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyTransitionRulesElse" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyActivitiesHidden"
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyCode" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyCallOfServicesTop" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyCallOfServicesLeft" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyCallOfServicesWidth" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyCallOfServicesHeight" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyActivityExecutionsFinished" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyActivityExecutionsExecutionOf" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyActivityExecutionsCurrentUser" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyActivityExecutionsProcessExecution" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#ClassActivityExecutions" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#ClassAccessControlModes" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyAccessControlModesRoleRestrictedUse" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyAccessControlModesUser" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyAccessControlModesRoleRestrictedUserInherited" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyActivitiesAccessControlMode" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyActivitiesRestrictedRole" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyActivitiesRestrictedUser" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyProcessInitAccesControlMode" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyProcessInitRestrictedUser" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyProcessInitRestrictedRole" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyProcessDiagramData" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#ClassTokens" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyTokensVariable" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyTokensActivityExecution" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyTokensActivity" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyTokensCurrentUser" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#ClassNotificationMode" 
	AND predicate="http://www.w3.org/2000/01/rdf-schema#comment";
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#InstanceNotifyUser" 
	AND predicate="http://www.w3.org/2000/01/rdf-schema#comment";
DELETE FROM statements WHERE subject="" 
	AND (predicate="http://www.w3.org/2000/01/rdf-schema#isDefinedBy"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#seeAlso"
	OR predicate="http://www.w3.org/2000/01/rdf-schema#comment"
	OR predicate="http://www.w3.org/1999/02/22-rdf-syntax-ns#value");
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#InstanceNotifyNextActivityUsers" 
	AND predicate="http://www.w3.org/2000/01/rdf-schema#comment";
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#InstanceNotifyPreviousActivityUsers" 
	AND predicate="http://www.w3.org/2000/01/rdf-schema#comment";
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#InstanceNotifyRole" 
	AND predicate="http://www.w3.org/2000/01/rdf-schema#comment";
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyConnectorsNotificationModes" 
	AND predicate="http://www.w3.org/2000/01/rdf-schema#comment";
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyConnectorsNotifiedUser" 
	AND predicate="http://www.w3.org/2000/01/rdf-schema#comment";
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyConnectorsNotifiedRole" 
	AND predicate="http://www.w3.org/2000/01/rdf-schema#comment";
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyConnectorsNotificationMessage" 
	AND predicate="http://www.w3.org/2000/01/rdf-schema#comment";
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#ClassNotification" 
	AND predicate="http://www.w3.org/2000/01/rdf-schema#comment";
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyNotificationTo" 
	AND predicate="http://www.w3.org/2000/01/rdf-schema#comment";
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyNotificationConnector" 
	AND predicate="http://www.w3.org/2000/01/rdf-schema#comment";
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyNotificationProcessExecution" 
	AND predicate="http://www.w3.org/2000/01/rdf-schema#comment";
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyNotificationSent" 
	AND predicate="http://www.w3.org/2000/01/rdf-schema#comment";
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyNotificationDate" 
	AND predicate="http://www.w3.org/2000/01/rdf-schema#comment";
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyActivityExecutionsContextRecovery" 
	AND predicate="http://www.w3.org/2000/01/rdf-schema#comment";
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#ClassControls" 
	AND predicate="http://www.w3.org/2000/01/rdf-schema#comment";
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#InstanceControlsForward" 
	AND predicate="http://www.w3.org/2000/01/rdf-schema#comment";
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#InstanceControlsBackward" 
	AND predicate="http://www.w3.org/2000/01/rdf-schema#comment";
DELETE FROM statements WHERE subject="http://www.tao.lu/middleware/wfEngine.rdf#PropertyActivitiesControls" 
	AND predicate="http://www.w3.org/2000/01/rdf-schema#comment";
DELETE FROM statements WHERE subject="" 
	AND predicate="http://www.w3.org/2000/01/rdf-schema#comment";


DELETE FROM statements WHERE subject='http://www.tao.lu/middleware/Rules.rdf#SecondOperand' AND
 (  predicate = 'http://www.w3.org/2000/01/rdf-schema#comment'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#seeAlso'
	OR predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#value' );
DELETE FROM statements WHERE subject='http://www.tao.lu/middleware/Rules.rdf#TermValue' AND
 (  predicate = 'http://www.w3.org/2000/01/rdf-schema#comment'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#seeAlso'
	OR predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#value' );
DELETE FROM statements WHERE subject='http://www.tao.lu/middleware/Rules.rdf#Empty' AND
 (  predicate = 'http://www.w3.org/2000/01/rdf-schema#comment'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
	OR predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#value' );
DELETE FROM statements WHERE subject='http://www.tao.lu/middleware/Rules.rdf#SecondExpression' AND
 (  predicate = 'http://www.w3.org/2000/01/rdf-schema#comment'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#seeAlso'
	OR predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#value' );
DELETE FROM statements WHERE subject='http://www.tao.lu/middleware/Rules.rdf#FirstExpression' AND
 (  predicate = 'http://www.w3.org/2000/01/rdf-schema#comment'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#seeAlso'
	OR predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#value' );
DELETE FROM statements WHERE subject='http://www.tao.lu/middleware/Rules.rdf#ConstrcuctedSet' AND
 (  predicate = 'http://www.w3.org/2000/01/rdf-schema#comment'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#seeAlso'
	OR predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#value' );
DELETE FROM statements WHERE subject='http://www.tao.lu/middleware/Rules.rdf#Term' AND
 (  predicate = 'http://www.w3.org/2000/01/rdf-schema#comment'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#seeAlso'
	OR predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#value' );
DELETE FROM statements WHERE subject='http://www.tao.lu/middleware/Rules.rdf#LessThan' AND
 (  predicate = 'http://www.w3.org/2000/01/rdf-schema#comment'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#seeAlso'
	OR predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#value' );
DELETE FROM statements WHERE subject='http://www.tao.lu/middleware/Rules.rdf#LessThanOrEqual' AND
 (  predicate = 'http://www.w3.org/2000/01/rdf-schema#comment'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#seeAlso'
	OR predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#value' );
DELETE FROM statements WHERE subject='http://www.tao.lu/middleware/Rules.rdf#GreaterThanOrEqual' AND
 (  predicate = 'http://www.w3.org/2000/01/rdf-schema#comment'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#seeAlso'
	OR predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#value' );
DELETE FROM statements WHERE subject='http://www.tao.lu/middleware/Rules.rdf#GreaterThan' AND
 (  predicate = 'http://www.w3.org/2000/01/rdf-schema#comment'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#seeAlso'
	OR predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#value' );
DELETE FROM statements WHERE subject='http://www.tao.lu/middleware/Rules.rdf#NotEqual' AND
 (  predicate = 'http://www.w3.org/2000/01/rdf-schema#comment'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#seeAlso'
	OR predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#value' );
DELETE FROM statements WHERE subject='http://www.tao.lu/middleware/Rules.rdf#Equal' AND
 (  predicate = 'http://www.w3.org/2000/01/rdf-schema#comment'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#seeAlso'
	OR predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#value' );
DELETE FROM statements WHERE subject='http://www.tao.lu/middleware/Rules.rdf#DynamicText' AND
 (  predicate = 'http://www.w3.org/2000/01/rdf-schema#comment'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#seeAlso'
	OR predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#value' );
DELETE FROM statements WHERE subject='http://www.tao.lu/middleware/Rules.rdf#Predicate' AND
 (  predicate = 'http://www.w3.org/2000/01/rdf-schema#comment'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#seeAlso'
	OR predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#value' );
DELETE FROM statements WHERE subject='http://www.tao.lu/middleware/Rules.rdf#Subject' AND
 (  predicate = 'http://www.w3.org/2000/01/rdf-schema#comment'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#seeAlso'
	OR predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#value' );
DELETE FROM statements WHERE subject='http://www.tao.lu/middleware/Rules.rdf#Iterator' AND
 (  predicate = 'http://www.w3.org/2000/01/rdf-schema#comment'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#seeAlso'
	OR predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#value' );
DELETE FROM statements WHERE subject='http://www.tao.lu/middleware/Rules.rdf#HasOperator' AND
 (  predicate = 'http://www.w3.org/2000/01/rdf-schema#comment'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#seeAlso'
	OR predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#value' );
DELETE FROM statements WHERE subject='http://www.tao.lu/middleware/Rules.rdf#Multiply' AND
 (  predicate = 'http://www.w3.org/2000/01/rdf-schema#comment'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#seeAlso'
	OR predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#value' );
DELETE FROM statements WHERE subject='http://www.tao.lu/middleware/Rules.rdf#Division' AND
 (  predicate = 'http://www.w3.org/2000/01/rdf-schema#comment'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#seeAlso'
	OR predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#value' );
DELETE FROM statements WHERE subject='http://www.tao.lu/middleware/Rules.rdf#Minus' AND
 (  predicate = 'http://www.w3.org/2000/01/rdf-schema#comment'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#seeAlso'
	OR predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#value' );
DELETE FROM statements WHERE subject='http://www.tao.lu/middleware/Rules.rdf#Plus' AND
 (  predicate = 'http://www.w3.org/2000/01/rdf-schema#comment'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#seeAlso'
	OR predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#value' );
DELETE FROM statements WHERE subject='http://www.tao.lu/middleware/Rules.rdf#ArithmeticOperator' AND
 (  predicate = 'http://www.w3.org/2000/01/rdf-schema#comment'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#seeAlso'
	OR predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#value' );
DELETE FROM statements WHERE subject='http://www.tao.lu/middleware/Rules.rdf#FirstOperand' AND
 (  predicate = 'http://www.w3.org/2000/01/rdf-schema#comment'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#seeAlso'
	OR predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#value' );
DELETE FROM statements WHERE subject='http://www.tao.lu/middleware/Rules.rdf#Operation' AND
 (  predicate = 'http://www.w3.org/2000/01/rdf-schema#comment'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#seeAlso'
	OR predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#value' );
DELETE FROM statements WHERE subject='http://www.tao.lu/middleware/Rules.rdf#Const' AND
 (  predicate = 'http://www.w3.org/2000/01/rdf-schema#comment'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#seeAlso'
	OR predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#value' );
DELETE FROM statements WHERE subject='http://www.tao.lu/middleware/Rules.rdf#SubjectPredicateX' AND
 (  predicate = 'http://www.w3.org/2000/01/rdf-schema#comment'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#seeAlso'
	OR predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#value' );
DELETE FROM statements WHERE subject='http://www.tao.lu/middleware/Rules.rdf#Debug' AND
 (  predicate = 'http://www.w3.org/2000/01/rdf-schema#comment'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#seeAlso'
	OR predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#value' );
DELETE FROM statements WHERE subject='http://www.tao.lu/middleware/Rules.rdf#asLogicalOperator' AND
 (  predicate = 'http://www.w3.org/2000/01/rdf-schema#comment'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#seeAlso'
	OR predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#value' );
DELETE FROM statements WHERE subject='http://www.tao.lu/middleware/Rules.rdf#And' AND
 (  predicate = 'http://www.w3.org/2000/01/rdf-schema#comment'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#seeAlso'
	OR predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#value' );
DELETE FROM statements WHERE subject='http://www.tao.lu/middleware/Rules.rdf#Or' AND
 (  predicate = 'http://www.w3.org/2000/01/rdf-schema#comment'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#seeAlso'
	OR predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#value' );
DELETE FROM statements WHERE subject='http://www.tao.lu/middleware/Rules.rdf#Exists' AND
 (  predicate = 'http://www.w3.org/2000/01/rdf-schema#comment'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#seeAlso'
	OR predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#value' );
DELETE FROM statements WHERE subject='http://www.tao.lu/middleware/Rules.rdf#LogicalOperator' AND
 (  predicate = 'http://www.w3.org/2000/01/rdf-schema#comment'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#seeAlso'
	OR predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#value' );
DELETE FROM statements WHERE subject='http://www.tao.lu/middleware/Rules.rdf#TerminalExpression' AND
 (  predicate = 'http://www.w3.org/2000/01/rdf-schema#comment'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#seeAlso'
	OR predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#value' );
DELETE FROM statements WHERE subject='http://www.tao.lu/middleware/Rules.rdf#If' AND
 (  predicate = 'http://www.w3.org/2000/01/rdf-schema#comment'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#seeAlso'
	OR predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#value' );
DELETE FROM statements WHERE subject='http://www.tao.lu/middleware/Rules.rdf#Expression' AND
 (  predicate = 'http://www.w3.org/2000/01/rdf-schema#comment'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#seeAlso'
	OR predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#value' );
DELETE FROM statements WHERE subject='http://www.tao.lu/middleware/Rules.rdf#Rule' AND
 (  predicate = 'http://www.w3.org/2000/01/rdf-schema#comment'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#seeAlso'
	OR predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#value' );
DELETE FROM statements WHERE subject='http://www.tao.lu/middleware/Rules.rdf#i122115224931756' AND
 (  predicate = 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy' );
DELETE FROM statements WHERE subject='http://www.tao.lu/middleware/Rules.rdf#XPredicateObject' AND
 (  predicate = 'http://www.w3.org/2000/01/rdf-schema#comment'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#seeAlso'
	OR predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#value' );
DELETE FROM statements WHERE subject='http://www.tao.lu/middleware/Rules.rdf#Object' AND
 (  predicate = 'http://www.w3.org/2000/01/rdf-schema#comment'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#seeAlso'
	OR predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#value' );
DELETE FROM statements WHERE subject='http://www.tao.lu/middleware/Rules.rdf#Quantifier' AND
 (  predicate = 'http://www.w3.org/2000/01/rdf-schema#comment'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#seeAlso'
	OR predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#value' );
DELETE FROM statements WHERE subject='http://www.tao.lu/middleware/Rules.rdf#ItExistsUniqueItem' AND
 (  predicate = 'http://www.w3.org/2000/01/rdf-schema#comment'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#seeAlso'
	OR predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#value' );
DELETE FROM statements WHERE subject='http://www.tao.lu/middleware/Rules.rdf#ForAll' AND
 (  predicate = 'http://www.w3.org/2000/01/rdf-schema#comment'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#seeAlso'
	OR predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#value' );
DELETE FROM statements WHERE subject='http://www.tao.lu/middleware/Rules.rdf#Set' AND
 (  predicate = 'http://www.w3.org/2000/01/rdf-schema#comment'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#seeAlso'
	OR predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#value' );
DELETE FROM statements WHERE subject='http://www.tao.lu/middleware/Rules.rdf#TrippleMask' AND
 (  predicate = 'http://www.w3.org/2000/01/rdf-schema#comment'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#seeAlso'
	OR predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#value' );
DELETE FROM statements WHERE subject='http://www.tao.lu/middleware/Rules.rdf#HasSetOperator' AND
 (  predicate = 'http://www.w3.org/2000/01/rdf-schema#comment'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#seeAlso'
	OR predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#value' );
DELETE FROM statements WHERE subject='http://www.tao.lu/middleware/Rules.rdf#SetOperator' AND
 (  predicate = 'http://www.w3.org/2000/01/rdf-schema#comment'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#seeAlso'
	OR predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#value' );
DELETE FROM statements WHERE subject='http://www.tao.lu/middleware/Rules.rdf#Union' AND
 (  predicate = 'http://www.w3.org/2000/01/rdf-schema#comment'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#seeAlso'
	OR predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#value' );
DELETE FROM statements WHERE subject='http://www.tao.lu/middleware/Rules.rdf#Intersect' AND
 (  predicate = 'http://www.w3.org/2000/01/rdf-schema#comment'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#seeAlso'
	OR predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#value' );
DELETE FROM statements WHERE subject='http://www.tao.lu/middleware/Rules.rdf#SubSets' AND
 (  predicate = 'http://www.w3.org/2000/01/rdf-schema#comment'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#seeAlso'
	OR predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#value' );
DELETE FROM statements WHERE subject='http://www.tao.lu/middleware/Rules.rdf#Assignment' AND
 (  predicate = 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#seeAlso'
	OR predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#value' );
DELETE FROM statements WHERE subject='http://www.tao.lu/middleware/Rules.rdf#Variable' AND
 (  predicate = 'http://www.w3.org/2000/01/rdf-schema#comment'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#seeAlso'
	OR predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#value' );
DELETE FROM statements WHERE subject='http://www.tao.lu/middleware/Rules.rdf#Value' AND
 (  predicate = 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#seeAlso'
	OR predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#value' );
DELETE FROM statements WHERE subject='http://www.tao.lu/middleware/Rules.rdf#IsNull' AND
 (  predicate = 'http://www.w3.org/2000/01/rdf-schema#comment'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#seeAlso'
	OR predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#value' );
DELETE FROM statements WHERE subject='http://www.tao.lu/middleware/Rules.rdf#Concat' AND
 (  predicate = 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#seeAlso'
	OR predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#value' );
DELETE FROM statements WHERE subject='http://www.tao.lu/middleware/Rules.rdf#True' AND
 (  predicate = 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#seeAlso'
	OR predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#value' );
DELETE FROM statements WHERE subject='http://www.tao.lu/middleware/Rules.rdf#False' AND
 (  predicate = 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#seeAlso'
	OR predicate = 'http://www.w3.org/1999/02/22-rdf-syntax-ns#value' );
DELETE FROM statements WHERE subject='http://www.tao.lu/middleware/Rules.rdf#RuleEngine' AND
 (  predicate = 'http://www.w3.org/2000/01/rdf-schema#comment'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy'
	OR predicate = 'http://www.w3.org/2000/01/rdf-schema#seeAlso' );
