INSERT INTO "statements" ("modelID", "subject", "predicate", "object", "l_language", "author", "stread", "stedit", "stdelete") VALUES
(15, 'http://www.tao.lu/middleware/taoqual.rdf#NotificationMode', 'http://www.w3.org/2000/01/rdf-schema#comment', '', 'EN', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#NotificationMode', 'http://www.w3.org/2000/01/rdf-schema#label', 'Notification Mode', 'EN', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#NotificationMode', 'http://www.w3.org/2000/01/rdf-schema#subClassOf', 'http://www.tao.lu/middleware/taoqual.rdf#i119969482458020', '', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),

(15, 'http://www.tao.lu/middleware/taoqual.rdf#NotifyUser', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type', 'http://www.tao.lu/middleware/taoqual.rdf#NotificationMode', '', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#NotifyUser', 'http://www.w3.org/2000/01/rdf-schema#comment', '', 'EN ', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#NotifyUser', 'http://www.w3.org/2000/01/rdf-schema#label', 'Notify User', 'EN ', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),

(15, 'http://www.tao.lu/middleware/taoqual.rdf#NotifyNextActivityUsers', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type', 'http://www.tao.lu/middleware/taoqual.rdf#NotificationMode', '', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#NotifyNextActivityUsers', 'http://www.w3.org/2000/01/rdf-schema#comment', '', 'EN ', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#NotifyNextActivityUsers', 'http://www.w3.org/2000/01/rdf-schema#label', 'Notify Next Activity Users', 'EN ', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),

(15, 'http://www.tao.lu/middleware/taoqual.rdf#NotifyPreviousActivityUsers', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type', 'http://www.tao.lu/middleware/taoqual.rdf#NotificationMode', '', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#NotifyPreviousActivityUsers', 'http://www.w3.org/2000/01/rdf-schema#comment', '', 'EN ', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#NotifyPreviousActivityUsers', 'http://www.w3.org/2000/01/rdf-schema#label', 'Notify Previous Activity Users', 'EN ', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),

(15, 'http://www.tao.lu/middleware/taoqual.rdf#NotifyGroup', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type', 'http://www.tao.lu/middleware/taoqual.rdf#NotificationMode', '', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#NotifyGroup', 'http://www.w3.org/2000/01/rdf-schema#comment', '', 'EN ', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#NotifyGroup', 'http://www.w3.org/2000/01/rdf-schema#label', 'Notifiy Role', 'EN ', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),

(15, 'http://www.tao.lu/middleware/taoqual.rdf#Notify', 'http://www.w3.org/2000/01/rdf-schema#range', 'http://www.tao.lu/middleware/taoqual.rdf#NotificationMode', 'EN', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#Notify', 'http://www.tao.lu/datatypes/WidgetDefinitions.rdf#widget', 'http://www.tao.lu/datatypes/WidgetDefinitions.rdf#CheckBox', '', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#Notify', 'http://www.w3.org/2000/01/rdf-schema#comment', '', 'EN', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#Notify', 'http://www.w3.org/2000/01/rdf-schema#label', 'Notify', 'EN', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#Notify', 'http://www.w3.org/2000/01/rdf-schema#domain', 'http://www.tao.lu/middleware/taoqual.rdf#i118589215756172', '', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#Notify', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#Property', '', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),

(15, 'http://www.tao.lu/middleware/taoqual.rdf#UserNotified', 'http://www.w3.org/2000/01/rdf-schema#range', 'http://www.tao.lu/Ontologies/generis.rdf#User', 'EN', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#UserNotified', 'http://www.tao.lu/datatypes/WidgetDefinitions.rdf#widget', 'http://www.tao.lu/datatypes/WidgetDefinitions.rdf#CheckBox', '', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#UserNotified', 'http://www.w3.org/2000/01/rdf-schema#comment', '', 'EN', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#UserNotified', 'http://www.w3.org/2000/01/rdf-schema#label', 'Users to notify', 'EN', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#UserNotified', 'http://www.w3.org/2000/01/rdf-schema#domain', 'http://www.tao.lu/middleware/taoqual.rdf#i118589215756172', '', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#UserNotified', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#Property', '', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),

(15, 'http://www.tao.lu/middleware/taoqual.rdf#GroupNotified', 'http://www.w3.org/2000/01/rdf-schema#range', 'http://www.tao.lu/Ontologies/TAO.rdf#BackOffice', 'EN', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#GroupNotified', 'http://www.tao.lu/datatypes/WidgetDefinitions.rdf#widget', 'http://www.tao.lu/datatypes/WidgetDefinitions.rdf#CheckBox', '', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#GroupNotified', 'http://www.w3.org/2000/01/rdf-schema#comment', '', 'EN', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#GroupNotified', 'http://www.w3.org/2000/01/rdf-schema#label', 'Role\'s users to notify', 'EN', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#GroupNotified', 'http://www.w3.org/2000/01/rdf-schema#domain', 'http://www.tao.lu/middleware/taoqual.rdf#i118589215756172', '', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#GroupNotified', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#Property', '', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),

(15, 'http://www.tao.lu/middleware/taoqual.rdf#NotificationMessage', 'http://www.w3.org/2000/01/rdf-schema#range', 'http://www.w3.org/2000/01/rdf-schema#Literal', 'EN', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#NotificationMessage', 'http://www.tao.lu/datatypes/WidgetDefinitions.rdf#widget', 'http://www.tao.lu/datatypes/WidgetDefinitions.rdf#HTMLArea', '', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#NotificationMessage', 'http://www.w3.org/2000/01/rdf-schema#comment', '', 'EN', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#NotificationMessage', 'http://www.w3.org/2000/01/rdf-schema#label', 'Notification Message', 'EN', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#NotificationMessage', 'http://www.w3.org/2000/01/rdf-schema#domain', 'http://www.tao.lu/middleware/taoqual.rdf#i118589215756172', '', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#NotificationMessage', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#Property', '', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),

(15, 'http://www.tao.lu/middleware/taoqual.rdf#Notification', 'http://www.w3.org/2000/01/rdf-schema#comment', '', 'EN', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#Notification', 'http://www.w3.org/2000/01/rdf-schema#label', 'Notification', 'EN', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#Notification', 'http://www.w3.org/2000/01/rdf-schema#subClassOf', 'http://www.tao.lu/middleware/taoqual.rdf#i119969482458020', '', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),

(15, 'http://www.tao.lu/middleware/taoqual.rdf#NotificationTo', 'http://www.w3.org/2000/01/rdf-schema#range', 'http://www.tao.lu/Ontologies/generis.rdf#User', 'EN', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#NotificationTo', 'http://www.tao.lu/datatypes/WidgetDefinitions.rdf#widget', 'http://www.tao.lu/datatypes/WidgetDefinitions.rdf#ComboBox', '', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#NotificationTo', 'http://www.w3.org/2000/01/rdf-schema#comment', '', 'EN', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#NotificationTo', 'http://www.w3.org/2000/01/rdf-schema#label', 'User to notify', 'EN', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#NotificationTo', 'http://www.w3.org/2000/01/rdf-schema#domain', 'http://www.tao.lu/middleware/taoqual.rdf#Notification', '', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#NotificationTo', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#Property', '', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),

(15, 'http://www.tao.lu/middleware/taoqual.rdf#NotificationConnector', 'http://www.w3.org/2000/01/rdf-schema#range', 'http://www.tao.lu/middleware/taoqual.rdf#i118589215756172', 'EN', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#NotificationConnector', 'http://www.tao.lu/datatypes/WidgetDefinitions.rdf#widget', 'http://www.tao.lu/datatypes/WidgetDefinitions.rdf#ComboBox', '', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#NotificationConnector', 'http://www.w3.org/2000/01/rdf-schema#comment', '', 'EN', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#NotificationConnector', 'http://www.w3.org/2000/01/rdf-schema#label', 'Connector\'s notification', 'EN', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#NotificationConnector', 'http://www.w3.org/2000/01/rdf-schema#domain', 'http://www.tao.lu/middleware/taoqual.rdf#Notification', '', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#NotificationConnector', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#Property', '', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),

(15, 'http://www.tao.lu/middleware/taoqual.rdf#NotificationProcessExecution', 'http://www.w3.org/2000/01/rdf-schema#range', 'http://www.tao.lu/middleware/taoqual.rdf#i119010455660544', 'EN', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#NotificationProcessExecution', 'http://www.tao.lu/datatypes/WidgetDefinitions.rdf#widget', 'http://www.tao.lu/datatypes/WidgetDefinitions.rdf#ComboBox', '', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#NotificationProcessExecution', 'http://www.w3.org/2000/01/rdf-schema#comment', '', 'EN', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#NotificationProcessExecution', 'http://www.w3.org/2000/01/rdf-schema#label', 'Process execution\'s notification', 'EN', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#NotificationProcessExecution', 'http://www.w3.org/2000/01/rdf-schema#domain', 'http://www.tao.lu/middleware/taoqual.rdf#Notification', '', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#NotificationProcessExecution', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#Property', '', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),

(15, 'http://www.tao.lu/middleware/taoqual.rdf#NotificationSent', 'http://www.w3.org/2000/01/rdf-schema#range', 'http://www.tao.lu/Ontologies/generis.rdf#Boolean', 'EN', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#NotificationSent', 'http://www.tao.lu/datatypes/WidgetDefinitions.rdf#widget', 'http://www.tao.lu/datatypes/WidgetDefinitions.rdf#RadioBox', '', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#NotificationSent', 'http://www.w3.org/2000/01/rdf-schema#comment', '', 'EN', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#NotificationSent', 'http://www.w3.org/2000/01/rdf-schema#label', 'Notification sent', 'EN', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#NotificationSent', 'http://www.w3.org/2000/01/rdf-schema#domain', 'http://www.tao.lu/middleware/taoqual.rdf#Notification', '', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#NotificationSent', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#Property', '', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),

(15, 'http://www.tao.lu/middleware/taoqual.rdf#NotificationDate', 'http://www.w3.org/2000/01/rdf-schema#range', 'http://www.w3.org/2000/01/rdf-schema#Literal', 'EN', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#NotificationDate', 'http://www.tao.lu/datatypes/WidgetDefinitions.rdf#widget', 'http://www.tao.lu/datatypes/WidgetDefinitions.rdf#Calendar', '', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#NotificationDate', 'http://www.w3.org/2000/01/rdf-schema#comment', '', 'EN', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#NotificationDate', 'http://www.w3.org/2000/01/rdf-schema#label', 'Notification date', 'EN', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#NotificationDate', 'http://www.w3.org/2000/01/rdf-schema#domain', 'http://www.tao.lu/middleware/taoqual.rdf#Notification', '', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#NotificationDate', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#Property', '', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]');

