INSERT INTO "statements" ("modelID", "subject", "predicate", "object", "l_language", "author", "stread", "stedit", "stdelete") VALUES

(15, 'http://www.tao.lu/middleware/taoqual.rdf#Controls', 'http://www.w3.org/2000/01/rdf-schema#comment', '', 'EN', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#Controls', 'http://www.w3.org/2000/01/rdf-schema#label', 'Controls', 'EN', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#Controls', 'http://www.w3.org/2000/01/rdf-schema#subClassOf', 'http://www.tao.lu/middleware/taoqual.rdf#i119969482458020', '', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),

(15, 'http://www.tao.lu/middleware/taoqual.rdf#ForwardControl', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type', 'http://www.tao.lu/middleware/taoqual.rdf#Controls', '', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#ForwardControl', 'http://www.w3.org/2000/01/rdf-schema#comment', '', 'EN ', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#ForwardControl', 'http://www.w3.org/2000/01/rdf-schema#label', 'Forward', 'EN ', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),

(15, 'http://www.tao.lu/middleware/taoqual.rdf#BackwardControl', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type', 'http://www.tao.lu/middleware/taoqual.rdf#Controls', '', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#BackwardControl', 'http://www.w3.org/2000/01/rdf-schema#comment', '', 'EN ', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#BackwardControl', 'http://www.w3.org/2000/01/rdf-schema#label', 'Backward', 'EN ', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),

(15, 'http://www.tao.lu/middleware/taoqual.rdf#ActivityControl', 'http://www.w3.org/2000/01/rdf-schema#range', 'http://www.tao.lu/middleware/taoqual.rdf#Controls', 'EN', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#ActivityControl', 'http://www.tao.lu/datatypes/WidgetDefinitions.rdf#widget', 'http://www.tao.lu/datatypes/WidgetDefinitions.rdf#CheckBox', '', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#ActivityControl', 'http://www.w3.org/2000/01/rdf-schema#comment', '', 'EN', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#ActivityControl', 'http://www.w3.org/2000/01/rdf-schema#label', 'Activity controls', 'EN', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#ActivityControl', 'http://www.w3.org/2000/01/rdf-schema#domain', 'http://www.tao.lu/middleware/taoqual.rdf#i118588757437650', '', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(15, 'http://www.tao.lu/middleware/taoqual.rdf#ActivityControl', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#Property', '', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]');
