INSERT INTO `statements` (`modelID`, `subject`, `predicate`, `object`, `l_language`, `author`, `stread`, `stedit`, `stdelete`) VALUES
(10, 'http://www.tao.lu/Ontologies/TAOItem.rdf#QTI', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type', 'http://www.tao.lu/Ontologies/TAOItem.rdf#ItemModels', '', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(10, 'http://www.tao.lu/Ontologies/TAOItem.rdf#QTI', 'http://www.tao.lu/Ontologies/TAOItem.rdf#SWFFile', 'QTI.swf???', 'EN ', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(10, 'http://www.tao.lu/Ontologies/TAOItem.rdf#QTI', 'http://www.tao.lu/Ontologies/TAOItem.rdf#i12580164649880', '/taoItems/QtiAuthoring/index', 'EN ', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(10, 'http://www.tao.lu/Ontologies/TAOItem.rdf#QTI', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#value', '', 'EN ', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(10, 'http://www.tao.lu/Ontologies/TAOItem.rdf#QTI', 'http://www.w3.org/2000/01/rdf-schema#comment', 'IMS Question and Test Interoperability', 'EN ', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(10, 'http://www.tao.lu/Ontologies/TAOItem.rdf#QTI', 'http://www.w3.org/2000/01/rdf-schema#label', 'QTI', 'EN ', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(10, 'http://www.tao.lu/Ontologies/TAOItem.rdf#QTI', 'http://www.w3.org/2000/01/rdf-schema#seeAlso', '', 'EN ', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]'),
(10, 'http://www.tao.lu/Ontologies/TAOItem.rdf#QTI', 'http://www.w3.org/2000/01/rdf-schema#isDefinedBy', '  ', 'EN ', 'generis', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]', 'yyy[admin,administrators,authors]');

INSERT INTO `statements` (`modelID`, `subject`, `predicate`, `object`, `l_language`, `author`, `stread`, `stedit`, `stdelete`) VALUES
(3, 'http://www.tao.lu/datatypes/WidgetDefinitions.rdf#Authoring', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type', 'http://www.tao.lu/datatypes/WidgetDefinitions.rdf#WidgetClass', '', 'generis', 'yyy[]', 'yy-[]', 'y--[Administrators]'),
(3, 'http://www.tao.lu/datatypes/WidgetDefinitions.rdf#Authoring', 'http://www.w3.org/2000/01/rdf-schema#label', 'Authoring', 'EN', 'generis', 'yyy[]', 'yy-[]', 'y--[Administrators]'),
(3, 'http://www.tao.lu/datatypes/WidgetDefinitions.rdf#Authoring', 'http://www.w3.org/2000/01/rdf-schema#comment', 'Open a tool to edit special content', 'EN', 'generis', 'yyy[]', 'yy-[]', 'y--[Administrators]'),
(3, 'http://www.tao.lu/datatypes/WidgetDefinitions.rdf#Authoring', 'http://www.tao.lu/datatypes/WidgetDefinitions.rdf#rangeConstraint', 'http://www.tao.lu/datatypes/WidgetDefinitions.rdf#rangeConstraint-Resource', '', 'generis', 'yyy[]', 'yy-[]', 'y--[Administrators]');